In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as pld

In [2]:
from sklearn.datasets import fetch_california_housing

In [3]:
data = fetch_california_housing()
data

{'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
           37.88      , -122.23      ],
        [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
           37.86      , -122.22      ],
        [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
           37.85      , -122.24      ],
        ...,
        [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
           39.43      , -121.22      ],
        [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
           39.43      , -121.32      ],
        [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
           39.37      , -121.24      ]]),
 'target': array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894]),
 'frame': None,
 'target_names': ['MedHouseVal'],
 'feature_names': ['MedInc',
  'HouseAge',
  'AveRooms',
  'AveBedrms',
  'Population',
  'AveOccup',
  'Latitude',
  'Longitude'],
 'DESCR': '.. _california_housing_dataset:\n\nCalifornia Housing dataset\n--------------------------\n\n**Data Set Characteristics:**\n\n:Number of Instances: 20640\n\n:Number of Attributes: 8 numeric, predictive attributes and the target\n\n:Attribute Information:\n    - MedInc        median income in block group\n    - HouseAge      median house age in block group\n    - AveRooms      average number of rooms per household\n    - AveBedrms     average number of bedrooms per household\n    - Population    block group population\n    - AveOccup      average number of household members\n    - Latitude      block group latitude\n    - Longitude     block group longitude\n\n:Missing Attribute Values: None\n\nThis dataset was obtained from the StatLib repository.\nhttps://www.dcc.fc.up.pt/~ltorgo/Regression/cal_housing.html\n\nThe target variable is the median house value for California districts,\nexpressed in hundreds of thousands of dollars ($100,000).\n\nThis dataset was derived from the 1990 U.S. census, using one row per census\nblock group. A block group is the smallest geographical unit for which the U.S.\nCensus Bureau publishes sample data (a block group typically has a population\nof 600 to 3,000 people).\n\nA household is a group of people residing within a home. Since the average\nnumber of rooms and bedrooms in this dataset are provided per household, these\ncolumns may take surprisingly large values for block groups with few households\nand many empty houses, such as vacation resorts.\n\nIt can be downloaded/loaded using the\n:func:`sklearn.datasets.fetch_california_housing` function.\n\n.. rubric:: References\n\n- Pace, R. Kelley and Ronald Barry, Sparse Spatial Autoregressions,\n  Statistics and Probability Letters, 33:291-297, 1997.\n'}

In [4]:
data.target

array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894])

In [6]:
#Make table :
df = pd.DataFrame(data.data , columns=data.feature_names)
df

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25
...,...,...,...,...,...,...,...,...
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22
20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32
20639,2.3886,16.0,5.254717,1.162264,1387.0,2.616981,39.37,-121.24

In [7]:
X,y = fetch_california_housing(return_X_y=True)
print(X.shape)
print(X[2])
print(X[[0,1]])
print(X[(0,1)])
print(X[[0,1],[1,2]])
print(X[0,1])

(20640, 8)
[   7.2574       52.            8.28813559    1.07344633  496.
    2.80225989   37.85       -122.24      ]
[[ 8.32520000e+00  4.10000000e+01  6.98412698e+00  1.02380952e+00
   3.22000000e+02  2.55555556e+00  3.78800000e+01 -1.22230000e+02]
 [ 8.30140000e+00  2.10000000e+01  6.23813708e+00  9.71880492e-01
   2.40100000e+03  2.10984183e+00  3.78600000e+01 -1.22220000e+02]]
41.0
[41.          6.23813708]
41.0

In [8]:
#Add target (Price) columns to table:
df2 = df.copy()
df["Target"]= data.target
df2

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25
...,...,...,...,...,...,...,...,...
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22
20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32
20639,2.3886,16.0,5.254717,1.162264,1387.0,2.616981,39.37,-121.24

In [9]:
#Soarting
df2.sort_values(by="HouseAge", ascending = False)

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
18881,2.3000,52.0,3.594203,1.246377,173.0,2.507246,38.10,-122.25
1671,3.6154,52.0,5.616016,1.147844,1076.0,2.209446,38.06,-122.21
19116,3.1711,52.0,5.058309,1.011662,712.0,2.075802,38.23,-122.65
19516,1.3036,52.0,9.136364,1.590909,74.0,3.363636,37.64,-121.01
16200,1.8261,52.0,4.251613,0.993548,1368.0,4.412903,37.95,-121.27
...,...,...,...,...,...,...,...,...
12077,6.2308,2.0,8.801008,1.373804,5964.0,3.004534,33.87,-117.64
18972,5.2636,1.0,7.694030,1.279851,872.0,3.253731,38.23,-122.00
12286,1.6250,1.0,3.000000,1.000000,8.0,4.000000,33.86,-116.95
3130,4.8750,1.0,5.533333,1.000000,32.0,2.133333,35.08,-117.95
19536,4.2500,1.0,20.125000,2.928571,402.0,3.589286,37.65,-120.93

In [10]:
#head/tail
df.head()
df.tail()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,Target
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09,0.781
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21,0.771
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22,0.923
20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32,0.847
20639,2.3886,16.0,5.254717,1.162264,1387.0,2.616981,39.37,-121.24,0.894

In [11]:
#logic function
df[df["Target"] >4.5]
#Error: df[3<df["Target"]<4]
#edite:
df[(df["Target"]>3)& (df["Target"]<4)]

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,Target
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422
103,2.5795,52.0,3.515498,1.143556,895.0,1.460033,37.81,-122.25,3.500
...,...,...,...,...,...,...,...,...,...
20502,2.9821,45.0,4.481481,0.925926,67.0,2.481481,34.33,-118.68,3.250
20503,8.2787,27.0,6.935065,1.103896,243.0,3.155844,34.33,-118.75,3.300
20504,7.3550,11.0,7.248670,0.978723,2526.0,3.359043,34.29,-118.73,3.439
20527,1.4653,7.0,3.525794,1.017857,4479.0,8.886905,38.54,-121.79,3.100
20533,4.2432,13.0,6.350569,1.053775,2553.0,2.640124,38.54,-121.67,3.265

In [13]:
#Loc : access to a room of table 
#row = index / columns = name
df2.loc[0,"HouseAge"]

41.0

In [40]:
#Insert Nan into a room of table:
df3 = df2.copy()
#df3=df2.loc[0,"HouseAge"]=np.nan
df3.loc[0, "HouseAge"]=np.nan
df3

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
0,8.3252,NaN,6.984127,1.023810,322.0,2.555556,37.88,-122.23
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25
...,...,...,...,...,...,...,...,...
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22
20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32
20639,2.3886,16.0,5.254717,1.162264,1387.0,2.616981,39.37,-121.24

In [43]:
df3.drop(columns=["HouseAge"],inplace=True)
df3

       MedInc  AveRooms  AveBedrms  Population  AveOccup  Latitude  Longitude
0      8.3252  6.984127   1.023810       322.0  2.555556     37.88    -122.23
1      8.3014  6.238137   0.971880      2401.0  2.109842     37.86    -122.22
2      7.2574  8.288136   1.073446       496.0  2.802260     37.85    -122.24
3      5.6431  5.817352   1.073059       558.0  2.547945     37.85    -122.25
4      3.8462  6.281853   1.081081       565.0  2.181467     37.85    -122.25
...       ...       ...        ...         ...       ...       ...        ...
20635  1.5603  5.045455   1.133333       845.0  2.560606     39.48    -121.09
20636  2.5568  6.114035   1.315789       356.0  3.122807     39.49    -121.21
20637  1.7000  5.205543   1.120092      1007.0  2.325635     39.43    -121.22
20638  1.8672  5.329513   1.171920       741.0  2.123209     39.43    -121.32
20639  2.3886  5.254717   1.162264      1387.0  2.616981     39.37    -121.24

[20640 rows x 7 columns]

In [45]:
df
df.loc[[0,1],"Population"]=np.nan
df

,MedInc,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,Target
0,8.3252,6.984127,1.023810,NaN,2.555556,37.88,-122.23,4.526
1,8.3014,6.238137,0.971880,NaN,2.109842,37.86,-122.22,3.585
2,7.2574,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422
...,...,...,...,...,...,...,...,...
20635,1.5603,5.045455,1.133333,845.0,2.560606,39.48,-121.09,0.781
20636,2.5568,6.114035,1.315789,356.0,3.122807,39.49,-121.21,0.771
20637,1.7000,5.205543,1.120092,1007.0,2.325635,39.43,-121.22,0.923
20638,1.8672,5.329513,1.171920,741.0,2.123209,39.43,-121.32,0.847
20639,2.3886,5.254717,1.162264,1387.0,2.616981,39.37,-121.24,0.894

In [47]:
# Is there any nan ?
df.isnull()
df.isnull().sum()

MedInc        0
AveRooms      0
AveBedrms     0
Population    2
AveOccup      0
Latitude      0
Longitude     0
Target        0
dtype: int64

In [52]:
#Fill Nan :
df
#df["HouseAge"].fillna(df["HouseAge"].mean())
#df["HouseAge"].mean()
df["Population"].fillna(df["Population"].mean(),inplace=True)
df

C:\Users\top\AppData\Local\Temp\ipykernel_2628\1138121337.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Population"].fillna(df["Population"].mean(),inplace=True)

,MedInc,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,Target
0,8.3252,6.984127,1.023810,1425.482944,2.555556,37.88,-122.23,4.526
1,8.3014,6.238137,0.971880,1425.482944,2.109842,37.86,-122.22,3.585
2,7.2574,8.288136,1.073446,496.000000,2.802260,37.85,-122.24,3.521
3,5.6431,5.817352,1.073059,558.000000,2.547945,37.85,-122.25,3.413
4,3.8462,6.281853,1.081081,565.000000,2.181467,37.85,-122.25,3.422
...,...,...,...,...,...,...,...,...
20635,1.5603,5.045455,1.133333,845.000000,2.560606,39.48,-121.09,0.781
20636,2.5568,6.114035,1.315789,356.000000,3.122807,39.49,-121.21,0.771
20637,1.7000,5.205543,1.120092,1007.000000,2.325635,39.43,-121.22,0.923
20638,1.8672,5.329513,1.171920,741.000000,2.123209,39.43,-121.32,0.847
20639,2.3886,5.254717,1.162264,1387.000000,2.616981,39.37,-121.24,0.894

In [ ]:
from sklearn.datasets import load_iris

In [ ]:
data=load_iris()
data.data
#data.feature_names
#data
df3 = pd.DataFrame(data.data, columns=data.feature_names)
df3["Target"]=data.target
df3